name: videosdk_flutter_example
description: A Flutter project for VideoSDK Demonstration.

publish_to: "none"

version: 1.0.0+14
environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  videosdk: ^1.2.5
  http: ^1.1.0
  flutter_dotenv: ^5.0.2
  flutter_svg: ^2.0.2
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.2.3
  lottie: ^2.2.0
  responsive_framework: 1.1.1
  window_manager: ^0.3.4
  flutter_markdown: ^0.6.10
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0
  firebase_messaging: ^14.0.0
  shared_preferences: ^2.3.4
  dotenv: ^4.2.0
  uuid: ^4.5.1
  flutter_callkit_incoming: ^2.0.4+2
  rflutter_alert: ^2.0.7
  go_router: ^14.6.2

  
 
 

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
